# Generated by Django 4.2.5 on 2023-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
