# Generated by Django 4.2.5 on 2023-09-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0005_alter_emaildistribution_period'),
        ('users', '0005_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_distribution.message', verbose_name='Сообщение'),
        ),
    ]
