# Generated by Django 4.2.5 on 2023-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0002_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildistribution',
            name='emails',
            field=models.ManyToManyField(to='email_distribution.client', verbose_name='Клиенты'),
        ),
    ]
