# Generated by Django 4.2.5 on 2023-09-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0003_message_emaildistribution_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=None, verbose_name='Дата и время последней попытки')),
                ('response', models.BooleanField(default=False, verbose_name='Ответ почтового сервера')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_distribution.emaildistribution', verbose_name='Статус рассылки')),
            ],
        ),
    ]
