# Generated by Django 4.2.5 on 2023-10-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0004_alter_emaildistribution_finish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='status',
            new_name='mailing',
        ),
    ]
