# Generated by Django 4.2.5 on 2023-10-13 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_distribution', '0007_alter_logs_options_logs_mail_alter_logs_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
