# Generated by Django 4.2.5 on 2023-10-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0008_logs_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
