# Generated by Django 4.2.5 on 2023-10-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0009_delete_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildistribution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
